### ISSUE TITLE
Scale to hundreds of sites

### ISSUE THREAD

**Issue by iandunn** [ryelle/WordCamp-Style-Import#4]
The Import Style screen currently shows all available camps, but that won't be manageable in production, where there are close to 500.

We'll need a way to allow users to find a small number of relevant sites to consider. My first thought would be to allow them to assign multiple filters, like the theme that's used, the year of the camp, and the CSS preprocessor. 

We could also provide a search function, so if there's a particular city that they know has a good site, they can quickly find it.

Do those seem like good ideas, or can anyone think of something better?

**Comment by ryelle** [comment]
+1 for some default filters to pare down on how many camps are shown initially, maybe only the 50 most recent or something. Preprocessor & theme would be good for just browsing, while a search with city/year can get you right to a site if you know what you're looking for.

Just for brainstorming, could we also filter for sites based WordCamp data? like attendance, conference length, time of year…? Then you could get sites designed for a lot of attendees, or long schedules, or a matching season (admittedly this one wouldn't work globally)

**Comment by iandunn** [comment]
Yeah, we've got the data for estimated attendance, number of days, and dates :)

I think browsing by season is a cool concept, but you're right that it'd be complicated to implement it in a way that works across countries and cultures.

I wonder if there's a good way to browse by the colors that are used prominently? That might achieve similar results and be more universal?

**Comment by ryelle** [comment]
:) I was thinking about color but wasn't sure how we could get that... maybe self-reporting in the CSS editor, like the tags used in wp.org themes? I don't really like suggesting that, and we'd need to rely on WordCamp site devs to add them.

It would be intense, but we could process a screenshot for a few colors used?

**Comment by iandunn** [comment]
Yeah, if we ask them to self-report I doubt anyone would. Maybe there's an existing library out there that can process the mshots we already have, and then tell us what the most frequent 2-3 colors are?

**Comment by iandunn** [comment]
Filtering by color would probably be a v2 thing since it's not low hanging fruit, though.

**Comment by iandunn** [comment]
Migrated to Meta Trac:

https://meta.trac.wordpress.org/ticket/1112
