### ISSUE TITLE
Why have both Import and Preview?

### ISSUE THREAD

**Issue by iandunn** [ryelle/WordCamp-Style-Import#6]
What's the advantage of having both the Import and Preview options? I don't see much of a use case for importing directly, without going through the preview step.

Would it be simpler for users to just have them always go through the Preview process?

**Comment by ryelle** [comment]
Yeah, I don't think I intended for both to always be there, I just got Import working first, and wanted to leave both as options. If Preview works as we want, there isn't a need for Import.

**Comment by iandunn** [comment]
Awesome :)
