### ISSUE TITLE
Don't require matching themes to import

### ISSUE THREAD

**Issue by iandunn** [ryelle/WordCamp-Style-Import#7]
What's the reasoning behind requiring the current site to have the same theme as another site before it can be cloned?

I definitely think we should inform the user that the theme will be switched, but it seems like making them manually switch the theme before they can import is kind of a hassle, and right now there's no way for the user to know _why_ the button is disabled.

(This will be irrelevant if #6 determines that the Import functionality isn't needed)

**Comment by ryelle** [comment]
This was a technical limitation, since I was just copying over the CSS, it would look broken if the sites' HTML didn't match up - and I didn't want to switch up themes and have old theme settings revoked just because someone clicked "Import"

**Comment by iandunn** [comment]
Ah, cool. It sounds like we'll probably remove Import before the launch, based on #6, so this isn't an issue.
